### ISSUE TITLE
Custom Color

### ISSUE THREAD

**Issue by Rosuljon** [basilebong/segmented-control-css#24]
Is it possible to change color of selected button to any custom color? For example sc-[#fff] like that?

**Comment by basilebong** [comment]
No yet. But meanwhile, you can write your own CSS to add your color:

```css
.sc-myclass input + label::before{
  background: [your-bg-color];
}
.sc-myclass input[type="radio"]:checked + label {
        color: [your-font-color];
}
```
